dataset:
  d_type: train_0
  sequence_length: 11025
  ae_mode: True
dataloader:
  batch_size: 1024
  shuffle: True
model_name: ConvAE
model_path: None
model:
  sequence_length: 11025
  features: 2
  extracted_features: 4
  latent_size: 16
  kernel_size: 65
  stride: 16
precision: float32
train_epochs: 10
device: cuda