# specify device
device: cuda
log: True

# this is automatically set after a training session
evaluation:

# model and dataset depends on those parameters
prev_samples: 512
future_samples: 512

# specify model arguments
model:
  tag: LSTM/512-512
  name: LstmModel

  # arguments used for training the model
  train:
    epochs: 5
    save_every: 1

# specify dataset arguments
dataset: 
  name: train_0
  normalize: False

  # dataloader specific arguments
  loader:
    batch_size: 64
    shuffle: True
    num_workers: 2