device: mps
log: True
evaluation:
input_sequence: 512
output_sequence: 1
model:
  tag: LSTM/4-to-1
  name: LstmModel
  train:
    epochs: 1
    save_every: 1
dataset: 
  name: train_0
  loader:
    batch_size: 128
    shuffle: True
    num_workers: 6