dataset:
  d_type: train_0
  sequence_length: 11025
dataloader:
  batch_size: 1024
  shuffle: True
model_name: LSTM
model_path: None
model:
  features: 32
  lstm_layers: 4
  hidden_dim: 64
precision: float32
train_epochs: 10
device: cuda